In [ ]:
import numpy as np
#creating arrays
arr=np.array([1,2,3,4,5],dtype=float)
print(arr)

[1. 2. 3. 4. 5.]


In [ ]:
zeros=np.zeros((3,3),dtype=float)
print(zeros)
ones=np.ones((2,2),dtype=int)
print(ones)
arrange=np.arange(100)
print(arrange)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1 1]
 [1 1]]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]


In [ ]:
import numpy as np
arrange=np.arange(0,100,5)
print(arrange)

[ 0  5 10 15 20 25 30 35 40 45 50 55 60 65 70 75 80 85 90 95]


In [ ]:
#array manipulation
arr=np.array([1,2,3,4,5],dtype=int)
reshaped=arr.reshape(5,1)
print(reshaped)
#slicing array
sliced=arr[2:4]
print(sliced)
#transpose of array
a=np.array([1,2,3,4,5,6,7,8])
b=a.T
print(b)
#split
b=np.split(a,2)
print(b)

[[1]
 [2]
 [3]
 [4]
 [5]]
[3 4]
[1 2 3 4 5 6 7 8]
[array([1, 2, 3, 4]), array([5, 6, 7, 8])]


In [ ]:
#matix multiplication
a=np.array([[1,2],[3,4]])
b=np.array([[5,6],[7,8]])
c=np.dot(a,b)
print(c)
d=np.linalg.eig(c)
print(d)

[[19 22]
 [43 50]]
EigResult(eigenvalues=array([5.80198014e-02, 6.89419802e+01]), eigenvectors=array([[-0.75781077, -0.40313049],
       [ 0.65247439, -0.91514251]]))


In [ ]:
#matix multiplication
a=np.array([[1,2],[3,4]])
b=np.array([[5,6],[7,8]])
c=np.dot(a,b)
print(c)
d=np.linalg.eig(c)
print(d)

[[19 22]
 [43 50]]
EigResult(eigenvalues=array([5.80198014e-02, 6.89419802e+01]), eigenvectors=array([[-0.75781077, -0.40313049],
       [ 0.65247439, -0.91514251]]))


In [ ]:
import numpy as np
data=np.arange(0,1000,5)
d=np.savetxt("/content/lab.txt",data)
print(d)
print(data)

None
[  0   5  10  15  20  25  30  35  40  45  50  55  60  65  70  75  80  85
  90  95 100 105 110 115 120 125 130 135 140 145 150 155 160 165 170 175
 180 185 190 195 200 205 210 215 220 225 230 235 240 245 250 255 260 265
 270 275 280 285 290 295 300 305 310 315 320 325 330 335 340 345 350 355
 360 365 370 375 380 385 390 395 400 405 410 415 420 425 430 435 440 445
 450 455 460 465 470 475 480 485 490 495 500 505 510 515 520 525 530 535
 540 545 550 555 560 565 570 575 580 585 590 595 600 605 610 615 620 625
 630 635 640 645 650 655 660 665 670 675 680 685 690 695 700 705 710 715
 720 725 730 735 740 745 750 755 760 765 770 775 780 785 790 795 800 805
 810 815 820 825 830 835 840 845 850 855 860 865 870 875 880 885 890 895
 900 905 910 915 920 925 930 935 940 945 950 955 960 965 970 975 980 985
 990 995]


In [ ]:
import numpy as np
a=np.random.rand()

print(a)

0.9569699039864433


In [ ]:
c=np.array([[1,2],[3,4]])
print(c.ndim)
print(c.shape)
print(type(c))

2
(2, 2)
<class 'numpy.ndarray'>


In [ ]:
import numpy as np
a=np.linspace(0.8,2,5)
print(a)

[0.8 1.1 1.4 1.7 2. ]


In [ ]:
b=np.arange(0,5)
print(b)
c=np.arange(24).reshape(3,2,4)
print(c)

[0 1 2 3 4]
[[[ 0  1  2  3]
  [ 4  5  6  7]]

 [[ 8  9 10 11]
  [12 13 14 15]]

 [[16 17 18 19]
  [20 21 22 23]]]


In [ ]:
a=np.array([[1,2],[3,4]])
b=np.array([[5,6],[3,4]])
print(a*b)
print(a@b)
c=np.dot(a,b)
print(c)

[[ 5 12]
 [ 9 16]]
[[11 14]
 [27 34]]
[[11 14]
 [27 34]]


In [ ]:
from numpy import random
a=np.ones([2,3],dtype=int)
print(a)
print(a.sum())
print(a.sum(axis=0))

[[1 1 1]
 [1 1 1]]
6
[2 2 2]


number of rows become number of group..
column become rows,group become column

In [ ]:
from numpy import random
a=np.floor(np.random.random((2,12)))
print(a)
c=np.random.random([2,12])
print(c)
e=np.array([1,2,3,5,6,7])
print(e.resize(3,2))


[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [ ]:
print(a.cumsum(axis=1))
a=np.array([2,3,5,6])
print(a.cumsum())
a=np.array([1,2,3,4,5,6])

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
[ 2  5 10 16]


In [ ]:
a=np.array([1,2,3,5,6,7])
a.resize(2,3)
b=np.array([9,3,8,5,1,4])
b.resize(2,3)
print(np.vstack((a,b)))
print(np.hstack((a,b)))
c=np.arange(30).reshape(2,3,5)
print(c)
print(np.dstack(c))

[[[ 0 15]
  [ 1 16]
  [ 2 17]
  [ 3 18]
  [ 4 19]]

 [[ 5 20]
  [ 6 21]
  [ 7 22]
  [ 8 23]
  [ 9 24]]

 [[10 25]
  [11 26]
  [12 27]
  [13 28]
  [14 29]]]


**24-02-24**

In [ ]:
a1=np.eye(4)
print(a1)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [ ]:
a1=np.full((2,2),3)
print(a1)
print(a1.itemsize)

[[3 3]
 [3 3]]
8


In [ ]:
x=[1,2,3]
a=np.asarray(x)
print(a)
print(type(a))

[1 2 3]
<class 'numpy.ndarray'>


In [ ]:
x=np.array([1,4,0],float)
y=np.array([2,2,1],float)
print(np.inner(x,y))
print(np.outer(x,y))
print(np.cross(x,y))


10.0
[[2. 2. 1.]
 [8. 8. 4.]
 [0. 0. 0.]]
[ 4. -1. -6.]


In [ ]:
a=np.array([1.2,2.8,3.5,4.0,5.6,6.1,7.8])
np.rint(a)

array([1., 3., 4., 4., 6., 6., 8.])

In [ ]:
a=np.array([10,6,8,4,48])
b=np.array([5,3,2,1,6])
np.true_divide(a,b)

array([2., 2., 4., 4., 8.])

In [ ]:
a=np.array([1,1,2,2,3,3])
np.unique(a)

array([1, 2, 3])

In [ ]:
a=np.array([[1,1],[2,3]])
b=np.array([[1,4],[6,3]])
np.union1d(a,b)

array([1, 2, 3, 4, 6])

In [ ]:
a=np.array([[1,1],[2,3]])
b=np.array([[1,4],[6,3]])
np.intersect1d(a,b)

array([1, 3])

In [ ]:
a=np.array([[1,1,2,3]])
b=np.array([[1,4,6,3]])
np.setdiff1d(a,b)

array([2])

In [ ]:
#hypotenues
a=8
b=6
c=np.hypot(a,b)
print(c)

10.0


In [ ]:
x=np.sin(0)
print(x)

0.0


In [14]:
a=np.array([10,21,30,40,50,60])
b=np.array([20,21,2,20,25,25])
d=np.divmod(a,b)
c=np.mod(a,b)
print(c)
print(d)

[10  0  0  0  0 10]
(array([ 0,  1, 15,  2,  2,  2]), array([10,  0,  0,  0,  0, 10]))


In [ ]:
a=np.array([10,21,30,40,50,60])
b=np.array([20,21,2,20,25,25])
c=np.divide(a,b)
print(c)

[ 0.5  1.  15.   2.   2.   2.4]


In [ ]:
a=np.array([10,21,30,40,50,60])
b=np.array([20,21,2,20,25,25])
c=np.multiply(a,b)
print(c)

[ 200  441   60  800 1250 1500]


In [ ]:
from numpy import random
x=random.normal(size=(2,3))
print(x)

[[-2.28521328  0.70503614 -0.29790369]
 [ 1.02765475 -0.5978811   1.16515452]]


In [ ]:
from numpy import random
x=random.normal(loc=1,scale=2,size=(2,3))
print(x)

[[-1.12698084 -4.33883962 -0.46599944]
 [-0.03518578 -0.83401198  1.37426357]]


In [ ]:
from numpy import random
x=random.binomial(n=12,p=0.5,size=10)
print(x)

[6 6 6 8 8 8 5 8 6 4]


In [16]:
from numpy import random
x=random.poisson(lam=2,size=10)
print(x)

[0 2 0 2 3 2 0 1 1 3]


In [ ]:
from numpy import random
x=random.choice([2,4])
print(x)

2


In [ ]:
from numpy import random
x=random.choice([3,5],p=[0.5,0.5],size=(3,5))
print(x)

[[3 3 5 3 3]
 [3 3 5 5 3]
 [5 3 3 3 5]]


**23-2-24 TASK-1 OPERATIONS:**

In [ ]:
a=5
b=6
c=a+b
print(c)
d=a-b
print(d)
a=6
b=4
e=a*b
print(e)

11
-1
24


In [ ]:
a=5
b=5
print(a==b)
print(a!=b)
d=7
e=5
print(d>=e)
print(d<=e)

True
False
True
False


In [ ]:
n=5
if(n>=0):
     print("positive")
else:
     print("negative")

positive


In [ ]:
n=-6
if(n>=0):
     print("positive")
elif(n<0):
     print("negative")
else:
      print("neutral")

negative


In [ ]:
n=7
for i in range(1,11,1):
  print(n,'*',i,'=',n*i)

7 * 1 = 7
7 * 2 = 14
7 * 3 = 21
7 * 4 = 28
7 * 5 = 35
7 * 6 = 42
7 * 7 = 49
7 * 8 = 56
7 * 9 = 63
7 * 10 = 70
